# Generated by Django 4.0.4 on 2022-06-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=1, max_digits=4)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('phonenumber', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('is_returnable', models.CharField(choices=[('RT', 'Returnable'), ('RP', 'Replacement')], max_length=2)),
                ('in_stock', models.CharField(choices=[('YS', 'Yes'), ('NO', 'No')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DL', 'Delivered'), ('OW', 'On The Way'), ('SH', 'Shipped')], max_length=2)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('items', models.ManyToManyField(to='core.storeitems')),
            ],
        ),
    ]
